// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNhCfxXmECULXmp4EkUz8Dci9zLc2uweg',
    appId: '1:741109787179:web:31019d6496e814cc29186e',
    messagingSenderId: '741109787179',
    projectId: 'final-project-f6115',
    authDomain: 'final-project-f6115.firebaseapp.com',
    storageBucket: 'final-project-f6115.appspot.com',
    measurementId: 'G-HEPQS44S33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVAN0HHSkYB05_mAP__RJ_yYuD8e0DPas',
    appId: '1:741109787179:android:398809511b5459a229186e',
    messagingSenderId: '741109787179',
    projectId: 'final-project-f6115',
    storageBucket: 'final-project-f6115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDa9xje3eFib90dSo1lOZqwkCVq6KffC0',
    appId: '1:741109787179:ios:feecbbd529277eb029186e',
    messagingSenderId: '741109787179',
    projectId: 'final-project-f6115',
    storageBucket: 'final-project-f6115.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}
